INSERT INTO students 
   VALUES('CAR', 'MAUDE', 2, 101);
INSERT INTO students 
   VALUES('KRISTENSEN', 'STORMY', 6, 112);
INSERT INTO students 
   VALUES('VANDERWOUDE', 'SHERWOOD', 3, 107);
INSERT INTO students 
   VALUES('NOGODA', 'ISMAEL', 0, 105);
INSERT INTO students 
   VALUES('DANESE', 'JANEE', 4, 111);
INSERT INTO students 
   VALUES('AMY', 'PATRINA', 1, 102);
INSERT INTO students 
   VALUES('PREHM', 'SHANEL', 0, 104);
INSERT INTO students 
   VALUES('GRUNIN', 'EMILE', 5, 109);
INSERT INTO students 
   VALUES('GELL', 'TAMI', 0, 104);
INSERT INTO students 
   VALUES('MADLOCK', 'RAY', 4, 110);
INSERT INTO students 
   VALUES('SUDA', 'DARLEEN', 4, 110);
INSERT INTO students 
   VALUES('DROP', 'SHERMAN', 0, 104);
INSERT INTO students 
   VALUES('PINNELL', 'ROBBY', 3, 107);
INSERT INTO students 
   VALUES('BROMLEY', 'EVELINA', 1, 103);
INSERT INTO students 
   VALUES('YUEN', 'ANIKA', 1, 103);
INSERT INTO students 
   VALUES('BUSTILLOS', 'HILMA', 0, 106);
INSERT INTO students 
   VALUES('GOODNOE', 'GAYLE', 4, 111);
INSERT INTO students 
   VALUES('BALBOA', 'MEL', 1, 103);
INSERT INTO students 
   VALUES('BARTKUS', 'REYNALDO', 1, 102);
INSERT INTO students 
   VALUES('GROENEWEG', 'CRYSTA', 3, 107);
INSERT INTO students 
   VALUES('HOUTCHENS', 'THEO', 0, 106);
INSERT INTO students 
   VALUES('GERSTEIN', 'AL', 5, 109);
INSERT INTO students 
   VALUES('MACIAG', 'CHET', 5, 109);
INSERT INTO students 
   VALUES('SAADE', 'TOBIE', 4, 110);
INSERT INTO students 
   VALUES('BRINE', 'FRANKLYN', 0, 106);
INSERT INTO students 
   VALUES('HANNEMANN', 'CHANTAL', 1, 102);
INSERT INTO students 
   VALUES('BYRUM', 'BENNIE', 0, 105);
INSERT INTO students 
   VALUES('NETZEL', 'JODY', 0, 105);
INSERT INTO students 
   VALUES('VANVLIET', 'COLLIN', 0, 106);
INSERT INTO students 
   VALUES('HONES', 'GUILLERMINA', 0, 104);
INSERT INTO students 
   VALUES('FLACHS', 'JEFFRY', 5, 109);
INSERT INTO students 
   VALUES('GRABILL', 'JULIENNE', 0, 106);
INSERT INTO students 
   VALUES('AREHART', 'VERTIE', 3, 107);
INSERT INTO students 
   VALUES('RUNKLE', 'MARCUS', 1, 102);
INSERT INTO students 
   VALUES('MOWATT', 'KITTIE', 0, 105);
INSERT INTO students 
   VALUES('HOOSOCK', 'LANCE', 1, 103);
INSERT INTO students 
   VALUES('LEAPER', 'ADRIAN', 4, 111);
INSERT INTO students 
   VALUES('PASSEY', 'RAYLENE', 4, 110);
INSERT INTO students 
   VALUES('NAKAHARA', 'SHERON', 0, 105);
INSERT INTO students 
   VALUES('STIRE', 'SHIRLEY', 6, 112);
INSERT INTO students 
   VALUES('RODDEY', 'CYRUS', 4, 110);
INSERT INTO students 
   VALUES('CRANMER', 'CAREY', 5, 109);
INSERT INTO students 
   VALUES('SCHUTZE', 'LANELLE', 5, 109);
INSERT INTO students 
   VALUES('FULVIO', 'ELTON', 4, 111);
INSERT INTO students 
   VALUES('HOESCHEN', 'LYNNETTE', 4, 108);
INSERT INTO students 
   VALUES('SOLOMAN', 'BRODERICK', 0, 106);
INSERT INTO students 
   VALUES('LAPLANT', 'SUMMER', 2, 101);
INSERT INTO students 
   VALUES('LUSKEY', 'BRITT', 4, 108);
INSERT INTO students 
   VALUES('JAGNEAUX', 'ELVIRA', 6, 112);
INSERT INTO students 
   VALUES('BIBB', 'SHANAE', 1, 103);
INSERT INTO students 
   VALUES('WIRTZFELD', 'DELORAS', 0, 106);
INSERT INTO students 
   VALUES('RANSLER', 'RODGER', 1, 102);
INSERT INTO students 
   VALUES('NABOZNY', 'CHRISSY', 3, 107);
INSERT INTO students 
   VALUES('ATWOOD', 'BETHEL', 5, 109);
INSERT INTO students 
   VALUES('CHIARAMONTE', 'NOVELLA', 2, 101);
INSERT INTO students 
   VALUES('TRAYWICK', 'KERI', 1, 102);
INSERT INTO students 
   VALUES('BRIGHTBILL', 'ANTONY', 1, 102);
INSERT INTO students 
   VALUES('HUANG', 'TAWANNA', 5, 109);
INSERT INTO students 
   VALUES('SANTORY', 'JORDON', 3, 107);
INSERT INTO students 
   VALUES('LARKINS', 'GAYLE', 4, 110);
